name: PUblish Release

on:
  push:
    branches:
      - 'master'
      - 'main'
    paths-ignore:
      - '**/README.md'
      - '**/LICENSE'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install shc
        run : |
          sudo apt-get install shc

      - name: Build
        run: make build
      
      - uses: BobAnkh/auto-generate-changelog@v1.2.5
        with:
          REPO_NAME: ''
          ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
          TYPE: 'feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,perf:Performance Improvements'

      - name: Generate release tag
        uses: amitsingh-007/next-release-tag@v2.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.release_tag }}
          files: retocli